### ISSUE TITLE
Missing pre-requisite step in readme - uncomment code

### ISSUE THREAD

**Issue by jasonicarter** [Faire/terraforming-snowflake#2]
Within the README.md `pre-requisite steps` you should include the step (or as optional) to uncomment code in `terraformer.py` unless this was accident and should be uncommented by default.
https://github.com/Faire/terraforming-snowflake/blob/847d401decd2639d545d28df3c5f11ede1b4d76c/terraformer/terraformer.py#L330-L333

**Comment by Pete-rePete** [comment]
Updated. Thanks again for opening these 👍
