### ISSUE TITLE
`tf_warehouses` IndexError: tuple index out of range 

### ISSUE THREAD

**Issue by jasonicarter** [Faire/terraforming-snowflake#3]
When running the code "as is" I receive an `IndexError: tuple index out of range`.

```python
Traceback (most recent call last):
  File "/Users/[...]/terraforming-snowflake/terraformer/terraformer.py", line 333, in <module>
    tf_warehouses(t)
  File "/Users/[...]/terraforming-snowflake/terraformer/terraformer.py", line 219, in tf_warehouses
    wh_dicts = [{k: row[i] for i, k in enumerate(columns)} for row in wh_data]
  File "/Users/[...]/terraforming-snowflake/terraformer/terraformer.py", line 219, in <listcomp>
    wh_dicts = [{k: row[i] for i, k in enumerate(columns)} for row in wh_data]
  File "/Users/[...]/terraforming-snowflake/terraformer/terraformer.py", line 219, in <dictcomp>
    wh_dicts = [{k: row[i] for i, k in enumerate(columns)} for row in wh_data]
IndexError: tuple index out of range
```

This is because when running on a single cluster you don't get back all of the columns you've listed out, namely,  `min_cluster_count`, `max_cluster_count`, `started_clusters` and `scaling_policy` columns are missing. You could do something fancy to check for this and/or update `wh_data` variable accordingly but as a workaround, I've just commented out all references to these columns in `terraforming.py` and `resources.py`. So far doing this hasn't broken anything 🤞🏾 
https://github.com/Faire/terraforming-snowflake/blob/847d401decd2639d545d28df3c5f11ede1b4d76c/terraformer/terraformer.py#L188-L218

**Comment by Pete-rePete** [comment]
Oh!!! This is incredibly good to know, really appreciate the heads up @jasonicarter. I'll add a fix and resolve this :) 

(I just realized I didn't have notifications turned on for issues, fixed)

**Comment by Pete-rePete** [comment]
Updated. Thanks again for opening these 👍
